### ISSUE TITLE
`mock` library missing from `requirements.txt`

### ISSUE THREAD

**Issue by eric-optimizely** [prezi/repoguard#10]
It appears that the [`requirements.txt` file](https://github.com/prezi/repoguard/blob/master/requirements.txt) is missing the [`mock` library](https://pypi.python.org/pypi/mock), which is used by [`repoguard.py`](https://github.com/prezi/repoguard/blob/master/repoguard.py#L16).  The following is from my shell with a fresh install.

```
$ virtualenv virtualenv
$ source virtualenv/bin/activate
$ pip install -r requirements.txt 
$ python repoguard.py --help
Traceback (most recent call last):
  File "repoguard.py", line 16, in <module>
    from mock import Mock
ImportError: No module named mock
```

**Comment by kepten** [comment]
fixed (https://github.com/prezi/repoguard/commit/86260a78f26bb4c5053da3d9db057c5b68126fef), thanks!
