### ISSUE TITLE
Installation instructions are incomplete

### ISSUE THREAD

**Issue by eric-optimizely** [prezi/repoguard#6]
The `README` does not make it clear how repoguard is installed. The following steps from the Installation section, for example:
```
$ virtualenv virtualenv
$ . virtualenv/bin/activate
$ pip install -r requirements.txt
$ python repoguard.py --config <file> --working-dir '../repos' --since '2014-08-01 00:00:00' --refresh
```
These instructions don't direct the user to download a copy of repoguard first, which makes it unclear which `requirements.txt` is supposed to applied (yours or ours) or how the `repoguard.py` file is supposed to exist on your machine already. It's left as an exercise for the reader, and think that could be improved.
It also instructs the user to apply the script to a directory called `repos/`, which suggests one config file for the collection of git repos they have on their machine. Is this accurate?

**Comment by kepten** [comment]
Fixed in https://github.com/prezi/repoguard/commit/1e80f73ec8fc719746fcd4e9afe2bce81f4eda2e.
